export const categories = [
  { name: 'Quran',   icon:"https://cdn.lordicon.com/mfqgdxxm.json"},
  { name: 'El-zero', icon:"https://cdn.lordicon.com/dtgezzsi.json"},
  { name: 'UniqeCoder',     icon:"https://cdn.lordicon.com/anihkfxp.json"},
  // { name: 'Cooding',     icon:""},
  { name: 'ReactJS', icon:"https://cdn.lordicon.com/dtgezzsi.json"},
  // { name: 'NextJS', icon:""  },
  { name: 'Education',     icon:"https://cdn.lordicon.com/wxnxiano.json"},
  { name: 'Podcast', icon:"https://cdn.lordicon.com/fpipqhrr.json" },
  { name: 'Football', icon:"https://cdn.lordicon.com/qoozyitg.json"},
  { name: 'Gaming', icon:"https://cdn.lordicon.com/ktxpktdd.json" },
  { name: 'Live', icon:"https://cdn.lordicon.com/smeqxwcv.json"},
  { name: 'Sport', icon:"https://cdn.lordicon.com/qoozyitg.json" },
  // { name: 'AI', icon:""},
  // { name: 'Sunnah', icon:"" },
  // { name: 'Hadeth', icon:"" },
  // { name: 'Gym', icon:"https://cdn.lordicon.com/wibomifa.json" },
  { name: 'Crypto', icon:"" },
];